### ISSUE TITLE
worked examples

### ISSUE THREAD

**Issue by jreuben11** [jonhoo/rust-for-rustaceans.com#36]
I love this book - learning so much beyond the basics.
However it is incredibly information dense and touches on many nieche corners of the language with descriptions and advice only - is there a repo of worked examples ?

**Comment by jonhoo** [comment]
Hi there! Glad you like it :)

No, there is not currently any such repository. The book is intentionally quite dense — I wanted it to act more like a series of pointers for what to explore and learn more about, rather than an exhaustive (and inevitably eventually outdated) reference. If you want to start an example repository though, I'm sure many people would be interested in collaborating on it!
